=== ChunHungLiu/bmin/doc/mandtd/bukka.dtd
<!-- bukka.dtd .......................................................... -->
<!-- Copyright (C) 2009 Jakub Zelenka ................................... -->
<!-- DTD for bukka.eu include files - projects' documentation ............-->

<!--================ Character mnemonic entities =========================-->

<!-- XHTML entities -->
<!ENTITY % HTMLlat1 PUBLIC "-//W3C//ENTITIES Latin 1 for XHTML//EN" "xhtml-lat1.ent">
%HTMLlat1;

<!ENTITY % HTMLsymbol
		 PUBLIC "-//W3C//ENTITIES Symbols for XHTML//EN" "xhtml-symbol.ent">
%HTMLsymbol;

<!ENTITY % HTMLspecial
		 PUBLIC "-//W3C//ENTITIES Special for XHTML//EN" "xhtml-special.ent">
%HTMLspecial;


<!--================ Bukka elements ======================================-->

<!-- root element -->
<!ELEMENT bukka (toc?, (h1 | h2 | h3 | h4 | p | div | img)*)>

<!-- menu generating element -->
<!ELEMENT toc EMPTY>

<!-- header elements -->
<!ENTITY % headers.children "(#PCDATA)">

<!ELEMENT h1 %headers.children;>
<!ELEMENT h2 %headers.children;>
<!ELEMENT h3 %headers.children;>
<!ELEMENT h4 %headers.children;>

<!ENTITY % h.atts "name NMTOKEN #IMPLIED class NMTOKENS #IMPLIED">
<!ATTLIST h2 %h.atts;>
<!ATTLIST h3 %h.atts;>
<!ATTLIST h4 %h.atts;>



<!-- text formator elements -->
<!ENTITY % text.form "c | b | i | a | val | nobr | span">


<!-- paragraph element -->
<!ELEMENT p (#PCDATA | %text.form; | exam | args | ul | ol | table | div)*>


<!-- font elements -->
<!ENTITY % font.children "(#PCDATA)">

<!-- code -->
<!ELEMENT c (#PCDATA | val)*>

<!-- bold -->
<!ELEMENT b %font.children;>

<!-- italic -->
<!ELEMENT i %font.children;>

<!-- value -->
<!ELEMENT val %font.children;>

<!-- no breaking line -->
<!ELEMENT nobr (#PCDATA | %text.form;)*>

<!-- arguments -->
<!ELEMENT args %font.children;>

<!-- html div -->
<!ELEMENT div (#PCDATA | %text.form; | div)*>
<!ATTLIST div id ID #IMPLIED
              class NMTOKENS #IMPLIED>

<!-- html span -->
<!ELEMENT span %font.children;>
<!ATTLIST span id ID #IMPLIED
               class NMTOKENS #IMPLIED>

<!-- sup a sub -->
<!ELEMENT sup (#PCDATA)>
<!ELEMENT sub (#PCDATA)>

<!-- html br - break line -->
<!ELEMENT br EMPTY>

<!-- exam element - usualy code exams -->
<!ELEMENT exam (#PCDATA | row)*>
<!ELEMENT row (#PCDATA)>

<!-- list element -->
<!-- unordinary -->
<!ELEMENT ul (li+)>
<!-- ordinary -->
<!ELEMENT ol (li+)>
<!-- list item -->
<!ELEMENT li (#PCDATA | %text.form;)*>


<!-- table elemnt -->
<!ELEMENT table (tr+)>
<!ATTLIST table type (examtable | opttable | params | data) "examtable">
<!ATTLIST table class NMTOKENS #IMPLIED>

<!ELEMENT tr ((th | td)+)>
<!ATTLIST tr class NMTOKENS #IMPLIED>

<!ENTITY % cell.children "(#PCDATA | %text.form; | ul | ol)*">
<!ELEMENT th %cell.children;>
<!ELEMENT td %cell.children;>
<!ATTLIST th class NMTOKENS #IMPLIED>
<!ATTLIST td class NMTOKENS #IMPLIED>


<!-- anchor (link) element -->
<!ELEMENT a (#PCDATA)>
<!ATTLIST a href CDATA #REQUIRED>
<!ATTLIST a class NMTOKENS #IMPLIED>


<!-- image element -->
<!ELEMENT img EMPTY>
<!ATTLIST img src CDATA #REQUIRED
              alt CDATA #IMPLIED>

=== ChunHungLiu/bmin/doc/manual.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bukka SYSTEM 'mandtd/bukka.dtd'>

<bukka>
	<h1>Bmin 1.0.0</h1>
	<toc/>
	
	<h2 name="install">Installation</h2>
	<p>
		Application is supported for Windows and Linux.  The installation depends on the platform.
	</p>
	
	<h3 name="win">Windows</h3>
	<p>
		For Windows the installer <a href="sources/bmin-1.0.0-win32.exe">bmin-1.0.0-win32.exe</a> is available. After
		executing the installer it is necessary to agree to the GPL version 3 license agreement. Then it is possible to
		create a shortcut in the <c>Start menu</c> as well as on the desktop. It is also possible to choose the install
		location (default is set to <c>C:\Program Files\Bmin</c>) and the name of the folder in the Start menu (default
		is <c>Bmin</c>). After installing the application it can be launched straight from the installer.
	</p>
	<p>
		During the installation the uninstaller is simultaneously created. The uninstaller is located in the same folder
		where the application was installed and called <c>Bmin Uninstall</c>. When creating a folder in the Start menu the
		uninstallation shortcut is located here.
	</p>
	
	<h3 name="linux">Linux</h3>
	<p>
		It is necessary to download the source code for Linux (<a href="sources/bmin-1.0.0.tgz">bmin-1.0.0.tgz</a>). The
		application depends on Qt library. This requires at least version 4.5 (version earlier than 4.5 will probably
		not compile).  Qt library must be installed even if the application only runs in a shell mode. The Mesa library
		version 7.8 (or later) and xorg-server version 1.7 or later must be also installed. 
	</p>
	<p>
		First, you need to unpack the gzip archive. The translation is done in two steps. First, in the directory with
		unpacked source code, run the <c>configure</c> file. It creates a <c>Makefile</c> and it can pass the arguments
		presented in the following table.
		<table type="examtable">
			<tr>
				<th>Option</th>
				<th>Description</th>
			</tr>
			<tr>
				<td><c>--prefix=<val>PATH</val></c></td>
				<td>Set installation directory prefix. Default value is <c>/usr</c></td>
			</tr>
			<tr>
				<td><c>--bindir=<val>PATH</val></c></td>
				<td>
					Set directory containing the application files Default value <c>$PREFIX/usr</c>,
					where <c>$PREFIX</c> is installation directory prefix.
				</td>
			</tr>
		</table>
		After creating a <c>Makefile</c> you need to call the <c>make</c> command and then <c>make install</c> to save the executable
		file <c>bmin</c> into place. The whole process might look like this: 
		<exam>
			<row># tar -xzf bmin-1.0.0.tgz</row>
			<row># cd bmin-1.0.0</row>
			<row># ./configure --prefix=/usr/local</row>
			<row># make</row>
			<row># make install</row>
			<row># bmin</row>
		</exam>
		The last command applies only if the program is intended to run in GUI mode. 
	</p>
	
	<h3 name="executing">Executing</h3>
	<p>
		The application has two modes. The first is the <b>Qt GUI mode</b> and the second is <b>Shell mode</b> that can
		be run using the option <c>--shell</c> or short <c>-s</c>. The Shell mode is available only for Linux. You can
		specify the startup option <c>--help</c> or <c>-h</c> for short which displays help. The last option is
		the <c>--version</c> or <c>-v</c> for short that displays the version number.
	</p>
	
	
	<h2 name="qtgui">Qt GUI mode</h2>
	<p>
		As the name suggests, the <b>Qt GUI mode</b> is executing in a graphical environment. After its launch it
		displays the main window with the menu bar, the main layout and the status bar. The main layout is divided into
		two parts - <b>top</b> and <b>bottom</b>.
	</p>
	<p>
		The <b>top part</b> is used for setting a Boolean function in its complete form and displaying the resulting
		minimized form of the function. The function can be entered directly into a text box or it can be used to create
		a function wizard (see below), which appears when you click on the button <c>New...</c>. If the specified
		function is set then the button <c>New...</c> is changed to <c>Edit...</c> and after clicking on it the function
		can be edited. The representation of logic functions can be set in a selection box <c>Representation of logic
			function:</c> where is the choice of the <c>Sum of Products</c>, which is a <b>DNF</b> (Disjunctive Normal
		Form), 	and <c>Products of Sums</c>, which is a <b>CNF</b> (Conjunctive Normal Form). The Minimize button is
		used to start the minimization. The resulting minimized function is displayed in the box <c>Minimal form:</c>
		which is read only.
	</p>
	<p>
		The <b>bottom part</b> contains four buttons on the left side. They are used for switching mode. The name of
		each mode is written on the button. The button with the current mode has black letters on white background. The
		easiest way to switch modes is to click on the button. The graphical application has four modes. The first is
		the Welcome mode which allows you to select another mode or open the About dialog. The other three modes are
		used for demonstration of the minimization of Boolean functions. Specifically, the Karnaugh map (K-map), the
		Boolean n-cube and of course the Quine-McCluskey algorithm. The following subsections describe how to set the
		Boolean function, above modes and some other functions.
	</p>
	
	<h3 name="fce">Setting Boolean function</h3>
	
	<h4 name="fce_direct">Direct setting</h4>
	<p>	
		Setting the function into the text field can take two forms. In the case of the Sum of Products representation
		the form is following:

		<exam>f(variable_list) = sum m(on_set) [ + sum d(dont_care_set)]</exam>

		where <c>variable_list</c> is the comma separated list of letters and <c>on_set</c> and <c>dont_care_set</c> are
		lists of numbers separated by commas. The list <c>on_set</c> is used to place the indexes of minterms with
		output value <c>1</c> (true state) and the list <c>dont_care_set</c> is for minterms whose output value is
		irrelevant (it is a forbidden state and such term is called <i>don't care term</i>). Square brackets indicate
		that the setting of these states is optional. But setting the true states is always required. If the function
		contains only false states then the list is empty. It writes as <c>m()</c>. Extra spaces and tabs are
		ignored. The specified function may therefore have the following form:

		<exam>f(d,c,b,a) = sum m(1,3,5,12,13) + sum d(2,10)</exam>

		In the case of Product of Sums representation the form is following:

		<exam>f(variable_list) = prod m(off_set) [ * prod d(dont_care_set)]</exam>

		Everything is basically the same as the Sum of Products representation, up to the fact that there are no
		minterms but maxterms, the middle sign is <c>*</c> instead of <c>+</c> and the list <c>off_set</c> is a comma
		separated list of indexes of the maxterms with output value <c>0</c> (false state). 
	</p>
	
	<h4 name="fce_wizard">Creating wizard</h4>
	<p>
		There is also a wizard for creating a logic function. The top four items are for setting the function name,
		selecting a representation and the number of variables and possibly enter the names of variables. After setting
		the number of variables the truth table is generated. There it is possible to change the output values in the
		column titled <c>Output</c> in several ways. The first way is by double clicking on the cell in
		the <c>Output</c> column and then a combo box will appear, and from there you can select the desired output
		value. The second way is selecting the desired output cell and then pressing the key with desired value (for
		example pressing key <c>1</c> for changing to output value 1). Another way is selecting the group of output
		cells and then open the context menu by clicking the right mouse button. There it is possible to set the output
		values for selected or all output values.  The function is saved by clicking on the <c>OK</c> button (or
		pressing <c>Enter</c> on the keyboard). Alternatively the function can be canceled by pressing the <c>Cancel</c>
		button (or pressing <c>Escape</c> on the keyboard).
	</p>
	
	<h3 name="map">Karnaugh map</h3>
	<p>
		The Karnaugh map is a tool for minimizing logic functions. It can be described as a two-dimensional array whose
		values are either 1 (true state) or 0 (false state) or X (forbidden state).  The position of each value is
		determined by the state of the function. It means that the position is uniquely determined for each minterm
		(maxterm) so that the minterms (maxterms) which differ in one variable are neighboring cells on the map. It
		makes it possible to cover all minimal terms. A more detailed description can be found
		on <a href="http://en.wikipedia.org/wiki/Karnaugh_map"> Wikipedia.org</a>.		
	</p>
	<p>
		The Karnaugh map in Bmin is drawn up to <b>6 variables</b>. The layout is divided into two parts. The left side
		displays the map and the right side displays the lists for displaying minterms (maxterms) and covers (more
		specifically terms of minimum coverage). These are only displayed if the checkbox <c>Show Covers</c> is
		marked. The map  is drawn once the function is set. There are two modes for the description of variables. The
		first shows the distribution in binary form and the second shows lines representing negations. Modes can be
		changed in the context menu by right clicking on the description of variables. You can also change the output
		values of terms by left clicking on the appropriate place on the map. The map changes are also directly
		displayed in the assignment of functions in the text box. The map is also linked with the list of the minterms
		(maxterms) and covers on the right side. Each selected minterm (maxterm) will change background color on its
		position on the map. Each selected cover highlights all minterms (maxterms) which are covered by it. The covers
		are also marked on the map using color boxes. The form of terms depends on the representation of the
